services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: supplysense-backend

    ports:
      - "8000:8000"

    restart: unless-stopped

    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: supplysense-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

    restart: unless-stopped
